# Pretty strict - we want high quality code!
run:
  timeout: 5m
  tests: true

linters:
  enable-all: true
  disable:
    # These ones are actually too much
    - wsl                # Whitespace linter (too opinionated about blank lines)
    - nlreturn           # Blank line before every return is silly
    - varnamelen         # i, j, k are fine for loops
    - testpackage        # Tests in same package are fine
    - paralleltest       # Not every test needs parallel
    - exhaustruct        # Don't need to initialize every struct field
    - gomnd              # We'll use constants where it makes sense
    - mnd                # Same as gomnd
    - godox              # TODO/FIXME comments are useful
    - funlen             # Some functions are naturally long
    - containedctx       # Context in structs is sometimes needed
    - tagliatelle        # Struct tag naming is project-specific
    - nonamedreturns     # Named returns can be useful
    - depguard           # We manage our own dependencies
    
    # Deprecated linters
    - deadcode
    - structcheck
    - varcheck
    - ifshort
    - golint
    - maligned
    - scopelint
    - exhaustivestruct

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
  
  gosec:
    severity: low      # Catch even minor security issues
    confidence: low
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
  
  gocyclo:
    min-complexity: 15  # Functions should be simple
  
  gocognit:
    min-complexity: 20  # Cognitive complexity limit
  
  dupl:
    threshold: 100      # Catch duplicate code
  
  lll:
    line-length: 120    # Reasonable line length
    tab-width: 4
  
  nakedret:
    max-func-lines: 0   # No naked returns at all!
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  
  revive:
    enable-all-rules: true
    rules:
      # Only disable the truly annoying ones
      - name: line-length-limit
        disabled: true
      - name: function-length
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: file-header
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: add-constant
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: unhandled-error
        disabled: true

issues:
  # Don't skip any issues
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # Be strict but reasonable about certain patterns
  exclude-rules:
    # Test files can skip some checks
    - path: _test\.go
      linters:
        - dupl         # Test code can be repetitive
        - gosec        # Test code can be less secure
        - errcheck     # Tests might ignore errors
    
    # Don't check error returns in deferred cleanup
    - source: "defer .*.Close"
      linters:
        - errcheck
    
    # Allow fmt.Print in main
    - path: main\.go
      linters:
        - forbidigo