# MAXIMUM STRICTNESS - We want ALL the checks!
run:
  timeout: 5m
  tests: true
  skip-dirs-use-default: true

linters:
  enable-all: true
  disable:
    # These are TOO annoying or conflicting
    - wsl                # Whitespace linter (too opinionated)
    - wrapcheck          # Forces wrapping errors everywhere
    - varnamelen         # Short var names are fine sometimes
    - testpackage        # Tests in same package are fine
    - paralleltest       # Not all tests need t.Parallel()
    - nlreturn           # Blank lines before return (too much)
    - gomnd              # Magic numbers - we'll document when needed
    - godox              # TODO/FIXME comments are fine for now
    - gochecknoglobals   # Some globals are fine
    - exhaustivestruct   # Don't need to init every field
    - funlen             # Function length - we'll be reasonable
    - gocognit           # Cognitive complexity - we'll be reasonable
    - cyclop             # Cyclomatic complexity - we'll be reasonable
    - depguard           # We'll manage our deps responsibly

linters-settings:
  # Make error messages better
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  # Catch shadowed variables
  govet:
    check-shadowing: true
    enable-all: true
  
  # Style rules
  revive:
    severity: error
    enable-all-rules: true
    rules:
      # Maybe too strict
      - name: cognitive-complexity
        disabled: true
      - name: function-length
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: file-header
        disabled: true
      - name: add-constant
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: unhandled-error
        disabled: true
  
  # Enforce test coverage
  gocover:
    threshold: 80
  
  # Complexity limits
  gocyclo:
    min-complexity: 15
  
  # Better naming
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
  
  # Security
  gosec:
    severity: high
    confidence: medium
  
  # No naked returns!
  nakedret:
    max-func-lines: 0  # No naked returns EVER
  
  # Struct tags
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
  
  # Line length
  lll:
    line-length: 120
    tab-width: 4

# Specific issues to ignore
issues:
  exclude-rules:
    # Test files can be more relaxed
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst