# Pretty strict - we want high quality code!
# But we've made some pragmatic choices after initial strict linting pass
run:
  timeout: 5m
  tests: true

linters:
  enable-all: true
  disable:
    # These ones are actually too much
    - wsl                # Whitespace linter (too opinionated about blank lines)
    - nlreturn           # Blank line before every return is silly
    - varnamelen         # i, j, k are fine for loops
    - testpackage        # Tests in same package are fine
    - paralleltest       # Not every test needs parallel
    - exhaustruct        # Don't need to initialize every struct field
    - gomnd              # We'll use constants where it makes sense
    - mnd                # Same as gomnd
    - godox              # TODO/FIXME comments are useful
    - funlen             # Some functions are naturally long
    - containedctx       # Context in structs is sometimes needed
    - tagliatelle        # Struct tag naming is project-specific
    - nonamedreturns     # Named returns can be useful
    - depguard           # We manage our own dependencies
    
    # Disabled after initial strict pass - may re-enable later
    - wrapcheck          # Too pedantic about wrapping errors from external packages
    - err113             # Dynamic errors are fine for now
    - gochecknoglobals   # Some globals are necessary (e.g., spinner definitions)
    - forbidigo          # fmt.Print is fine in main and CLI tools
    - revive             # Some of revive's rules are too opinionated
    - lll                # Line length - we have some long strings that are fine
    - gocognit           # Cognitive complexity - some functions are complex by nature
    - cyclop             # Cyclomatic complexity - similar to above
    - nestif             # Nested ifs are sometimes necessary
    - gocritic           # Some of its checks are too opinionated
    - ireturn            # Returning interfaces is fine
    - thelper            # t.Helper() is not always needed
    - goconst            # Not every repeated string needs to be a constant
    - noctx              # http requests without context are OK for simple cases
    - gocyclo            # Cyclomatic complexity - covered by gocognit
    - maintidx           # Maintainability index - functions are complex but readable
    - gci                # Import grouping - goimports handles this fine
    - gosec              # Security scanner - 0644 is fine for our files
    - prealloc           # Pre-allocating slices is a micro-optimization
    - forcetypeassert    # Type assertions are checked where needed
    - nilerr             # Returning nil on error is fine in tests
    
    # Deprecated linters
    - deadcode
    - structcheck
    - varcheck
    - ifshort
    - golint
    - maligned
    - scopelint
    - exhaustivestruct

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
  
  gosec:
    severity: low      # Catch even minor security issues
    confidence: low
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
  
  gocyclo:
    min-complexity: 15  # Functions should be simple
  
  gocognit:
    min-complexity: 20  # Cognitive complexity limit
  
  dupl:
    threshold: 100      # Catch duplicate code
  
  lll:
    line-length: 120    # Reasonable line length
    tab-width: 4
  
  nakedret:
    max-func-lines: 0   # No naked returns at all!
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  
  revive:
    enable-all-rules: true
    rules:
      # Only disable the truly annoying ones
      - name: line-length-limit
        disabled: true
      - name: function-length
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: file-header
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: add-constant
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: unhandled-error
        disabled: true

issues:
  # Don't skip any issues
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # Be strict but reasonable about certain patterns
  exclude-rules:
    # Test files can skip some checks
    - path: _test\.go
      linters:
        - dupl         # Test code can be repetitive
        - gosec        # Test code can be less secure
        - errcheck     # Tests might ignore errors
    
    # Don't check error returns in deferred cleanup
    - source: "defer .*.Close"
      linters:
        - errcheck
    
    # Allow fmt.Print in main
    - path: main\.go
      linters:
        - forbidigo
    
    # Type assertions in main.go Update methods are safe
    - path: main\.go
      text: "Error return value is not checked"
      linters:
        - errcheck
    
    # SetError calls when we're already returning the error
    - path: internal/orchestrator/orchestrator\.go
      text: "taskList.SetError"
      linters:
        - errcheck
    
    # Markdown renderer fallback is already handled
    - path: internal/chat/markdown\.go
      text: "glamour.NewTermRenderer"
      linters:
        - errcheck