# Markdown linting rules
default: true

# Line length
MD013:
  line_length: 120
  tables: false
  code_blocks: false

# Allow inline HTML
MD033: false

# First line doesn't have to be h1
MD041: false

# Allow duplicate headings
MD024: false